#!/usr/bin/env bash
#Script used to change the ip address of the localhost and facebook.com

cp /etc/hosts /tmp/hosts.tmp
sed 's/127.0.0.1 localhost/127.0.0.2 localhost/' /tmp/hosts.tmp > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

